filename_new_image: 'D:/Users/Ashafix/Documents/GitHub/NeuroMario/movies_images/new/new_{}.png'
filename_new_hash: 'D:/Users/Ashafix/Documents/GitHub/NeuroMario/movies_images/new/new_{}.hash'
filename_new_input: 'D:/Users/Ashafix/Documents/GitHub/NeuroMario/movies_images/new/new_{}.txt'